### ISSUE TITLE
歌词显示bug

### ISSUE THREAD

**Issue by KingProphild** [Folltoshe/lx-music-docs#24]
我之前用的双显示器，歌词我放在了第二块屏幕，现在回家里只有笔记本屏幕，打开落雪歌词就不能显示，任务栏能看见歌词的缩略图，猜测是软件记忆歌词位置在第二屏显示，导致我无法查看歌词。尝试通过卸载软件重装解决，无效，软件卸载不干净导致，只能自己去appdate文件夹手动删除软件配置文件重新设置。

**Comment by KingProphild** [comment]
已经解决，在设置里勾选中不允许歌词窗口拖出主窗口之外

**Comment by naiyQAQ** [comment]
这里是文档仓库，反馈非文档相关问题请去官方仓库
[桌面端](https://github.com/lyswhut/lx-music-desktop) 
[移动端](https://github.com/lyswhut/lx-music-mobile)
